# Generated by Django 3.2.6 on 2021-08-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
    ]
