# Generated by Django 3.2.6 on 2021-08-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_model_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about_me',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(null=True, upload_to='author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
